### ISSUE TITLE
Shader library compilation error: "location >= 0"

### ISSUE THREAD

**Issue by Nertsal** [kuviman/geng#51]
Stack trace:
```
[ERROR batbox::logger] panicked at 'assertion failed: location >= 0', /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/ugli-0.9.0/src/program.rs:72:13
[ERROR batbox::logger]    0: batbox::logger::init_with::{{closure}}
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/batbox-0.9.0/src/logger.rs:63:24
       1: std::panicking::rust_panic_with_hook
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
       2: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:586:13
       3: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
       4: rust_begin_unwind
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
       5: core::panicking::panic_fmt
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
       6: core::panicking::panic
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
       7: ugli::program::Program::new
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/ugli-0.9.0/src/program.rs:72:13
       8: geng::shader_lib::ShaderLib::compile
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/shader_lib/mod.rs:77:12
       9: <ugli::program::Program as geng::asset::LoadAsset>::load::{{closure}}
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/asset/mod.rs:37:16
      10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
      11: <core::pin::Pin<P> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
      12: <alloc::rc::Rc<T> as geng::asset::LoadAsset>::load::{{closure}}
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/asset/mod.rs:26:48
      13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
      14: <core::pin::Pin<P> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
      15: <arena_of_ideas::assets::Shaders as geng::asset::LoadAsset>::load::{{closure}}
                 at src/assets.rs:368:72
      16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
      17: <core::pin::Pin<P> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
      18: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/maybe_done.rs:95:38
      19: <arena_of_ideas::assets::Assets as geng::asset::LoadAsset>::load::{{closure}}::{{closure}}
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/async_await/join_mod.rs:95:13
      20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/poll_fn.rs:56:9
      21: <arena_of_ideas::assets::Assets as geng::asset::LoadAsset>::load::{{closure}}
                 at src/assets.rs:47:10
      22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19

      23: <core::pin::Pin<P> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
      24: arena_of_ideas::main::{{closure}}
                 at src/main.rs:210:90
      25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
      26: <geng::loading_screen::LoadingScreen<T,L,G> as geng::state::State>::transition
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/loading_screen/mod.rs:65:17
      27: <geng::state::manager::StateManager as geng::state::State>::update
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/state/manager.rs:30:39
      28: <geng::debug_overlay::DebugOverlay<T> as geng::state::State>::update
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/debug_overlay/mod.rs:37:9
      29: geng::context::run::RunState<T>::update
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/context.rs:151:13
      30: geng::context::run::{{closure}}
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/context.rs:193:13
      31: geng::context::run
                 at /home/nertsal/.cargo/registry/src/github.com-1ecc6299db9ec823/geng-0.9.0/src/context.rs:230:17
      32: arena_of_ideas::main
                 at src/main.rs:198:5
      33: core::ops::function::FnOnce::call_once
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
      34: std::sys_common::backtrace::__rust_begin_short_backtrace
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
      35: std::rt::lang_start::{{closure}}
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
      36: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
          std::panicking::try::do_call
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
          std::rt::lang_start_internal::{{closure}}
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
          std::panicking::try::do_call
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
          std::rt::lang_start_internal
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
      37: std::rt::lang_start
                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:144:17
      38: main
      39: <unknown>
      40: __libc_start_main
      41: _start
                 at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
```

**Comment by kuviman** [comment]
fixed
